"""
Session report generation — pulls attack results and recon history out of
SQLite and renders a Markdown summary suitable for OSWP/PEN-210 writeups.
"""

import datetime
from pathlib import Path

from core.models import get_results, get_recon_history

REPORT_DIR = Path("reports")


def _fmt_ts(ts: float) -> str:
    return datetime.datetime.fromtimestamp(ts).strftime("%Y-%m-%d %H:%M:%S")


def build_markdown_report(limit: int = 500) -> str:
    results = get_results(limit=limit)
    recon = get_recon_history(limit=limit)

    lines = []
    lines.append(f"# Wireless Assessment Report")
    lines.append(f"")
    lines.append(f"Generated: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    lines.append(f"")

    # ── Summary ────────────────────────────────────────────────────────────
    by_module = {}
    cracked_count = 0
    for r in results:
        by_module.setdefault(r["module"], 0)
        by_module[r["module"]] += 1
        result_str = (r["result"] or "").lower()
        if result_str and "not cracked" not in result_str and "exhausted" not in result_str and not result_str.startswith("error"):
            cracked_count += 1

    lines.append("## Summary")
    lines.append("")
    lines.append(f"- **{len(recon)}** access point(s) discovered (all-time, via recon)")
    lines.append(f"- **{len(results)}** attack result(s) recorded")
    lines.append(f"- **{cracked_count}** successful outcome(s)")
    if by_module:
        lines.append(f"- Modules used: {', '.join(f'{m} ({n})' for m, n in sorted(by_module.items()))}")
    lines.append("")

    # ── Recon inventory ────────────────────────────────────────────────────
    if recon:
        lines.append("## Discovered Access Points")
        lines.append("")
        lines.append("| BSSID | SSID | Vendor | Channel | Auth | Vulnerabilities | First Seen | Last Seen |")
        lines.append("|---|---|---|---|---|---|---|---|")
        for ap in recon:
            vulns = ", ".join(ap.get("vulnerabilities") or []) or "—"
            lines.append(
                f"| {ap['bssid']} | {ap['essid'] or '*hidden*'} | {ap['vendor'] or '—'} | "
                f"{ap['channel']} | {ap['privacy']} | {vulns} | "
                f"{_fmt_ts(ap['first_seen'])} | {_fmt_ts(ap['last_seen'])} |"
            )
        lines.append("")

    # ── Attack results, grouped by module ─────────────────────────────────
    if results:
        lines.append("## Attack Results")
        lines.append("")
        modules_seen = sorted(set(r["module"] for r in results))
        for module in modules_seen:
            module_results = [r for r in results if r["module"] == module]
            lines.append(f"### {module}")
            lines.append("")
            lines.append("| Time | Target BSSID | Target SSID | Result |")
            lines.append("|---|---|---|---|")
            for r in module_results:
                lines.append(
                    f"| {_fmt_ts(r['timestamp'])} | {r['target_bssid'] or '—'} | "
                    f"{r['target_ssid'] or '—'} | {r['result'] or '—'} |"
                )
            lines.append("")

    lines.append("---")
    lines.append("*Generated by wpx.py — for authorized testing on your own hardware/networks only.*")

    return "\n".join(lines)


def write_report(limit: int = 500) -> Path:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    content = build_markdown_report(limit=limit)
    ts = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    path = REPORT_DIR / f"report_{ts}.md"
    path.write_text(content)
    return path
